In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import tensorflow as tf
from tensorflow import keras
from torch import nn


In [ ]:

import torch
from torch import nn
#video implementation
class LayerNormalization():
    def __init__(self, parameters_shape, eps=1e-5):
        self.parameters_shape=parameters_shape
        self.eps=eps
        self.gamma = nn.Parameter(torch.ones(parameters_shape))
        self.beta =  nn.Parameter(torch.zeros(parameters_shape))

    def forward(self, input):
        dims = [-(i + 1) for i in range(len(self.parameters_shape))]
        mean = inputs.mean(dim=dims, keepdim=True)
        print(f"Mean \n ({mean.size()}): \n {mean}")
        var = ((inputs - mean) ** 2).mean(dim=dims, keepdim=True)
        std = (var + self.eps).sqrt()
        print(f"Standard Deviation \n ({std.size()}): \n {std}")
        y = (inputs - mean) / std
        print(f"y \n ({y.size()}) = \n {y}")
        out = self.gamma * y  + self.beta
        print(f"out \n ({out.size()}) = \n {out}")
        return out

In [ ]:
#my onw
class CustomLayerNorm(nn.Module):
    def __init__(self, normalized_shape, epsilon=1e-5):
        super(CustomLayerNorm, self).__init__()
        self.gamma = nn.Parameter(torch.ones(normalized_shape))
        self.beta = nn.Parameter(torch.zeros(normalized_shape))
        self.epsilon = epsilon

    def forward(self, x):
        # Calculate mean and std across the last dimension (features) for each sequence in the batch
        mean = x.mean(dim=-1, keepdim=True)
        std = x.std(dim=-1, keepdim=True)
        x_normalized = (x - mean) / (std + self.epsilon)

        # Apply gamma and beta, which are learned parameters for normalization
        # The shape of gamma and beta should match the feature size
        return self.gamma.unsqueeze(0).unsqueeze(0) * x_normalized + self.beta.unsqueeze(0).unsqueeze(0)




In [ ]:
# Sample input tensor with batch dimension (2, 2, 3)
torch.manual_seed(2)
x = torch.randn(2, 2, 3)
print("Input Tensor:\n", x)

layer_norm = CustomLayerNorm(normalized_shape=x.shape[2])
output_custom = layer_norm(x)
print("\nCustom Layer Norm Output:\n", output_custom)

layer_norm_video = LayerNormalization(parameters_shape=x.shape[2])
output_custom_video = layer_norm(x)
print("\n video Layer Norm Output:\n", output_custom_video)

layer_norm_builtin = nn.LayerNorm(normalized_shape=x.shape[2])
output_builtin = layer_norm_builtin(x)
print("\nPyTorch Layer Norm Output:\n", output_builtin)

Input Tensor:
 tensor([[[ 0.3923, -0.2236, -0.3195],
         [-1.2050,  1.0445, -0.6332]],

        [[ 0.5731,  0.5409, -0.3919],
         [-1.0427,  1.3186,  0.7476]]])

Custom Layer Norm Output:
 tensor([[[ 1.1457, -0.4487, -0.6971],
         [-0.8044,  1.1196, -0.3153]],

        [[ 0.6064,  0.5478, -1.1542],
         [-1.1233,  0.7934,  0.3299]]], grad_fn=<AddBackward0>)

 video Layer Norm Output:
 tensor([[[ 1.1457, -0.4487, -0.6971],
         [-0.8044,  1.1196, -0.3153]],

        [[ 0.6064,  0.5478, -1.1542],
         [-1.1233,  0.7934,  0.3299]]], grad_fn=<AddBackward0>)

PyTorch Layer Norm Output:
 tensor([[[ 1.4032, -0.5495, -0.8537],
         [-0.9851,  1.3713, -0.3861]],

        [[ 0.7427,  0.6709, -1.4136],
         [-1.3757,  0.9717,  0.4041]]], grad_fn=<NativeLayerNormBackward0>)


In [ ]:
#loks good thats it!